on: [push]

permissions:
  contents: read
  actions: write

jobs:
  releasenotes:
    runs-on: ubuntu-latest
    name: Generate release notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate release notes
        uses: kuvaus/changelog-releasenotes-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}

